# Generated by Django 3.0.9 on 2020-12-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='price',
            field=models.CharField(choices=[('6$', 6), ('11$', 12), ('15$', 24)], default='6$', max_length=10),
        ),
    ]
